= readme

== articles
http://stackoverflow.com/questions/30019585/log4j2-why-would-you-use-it-over-log4j
https://techblog.bozho.net/external-project-configuration/
https://news.ycombinator.com/item?id=14164662[Scalable, Lie-Detecting Timeserving with Roughtime]
https://news.ycombinator.com/item?id=14149186[Microsoft To-Do Preview]
https://news.ycombinator.com/item?id=14154378[Microsoft to shut down Wunderlist in favor of its new app, To-Do]
https://discordapp.com/
https://mastodon.social/
https://news.ycombinator.com/item?id=14145252[The History of Computer RPGs]
http://onemodel.org/
https://news.ycombinator.com/item?id=14133060[The 9-Minute Strength Workout – Well Guides]
https://news.ycombinator.com/item?id=14129543[Rope Science – Advanced computer science concepts behind the Xi editor]
https://news.ycombinator.com/item?id=14130241[Phishing with Unicode Domains]
https://news.ycombinator.com/item?id=14128145[Data structures and algorithms interview questions and their solutions]
https://news.ycombinator.com/item?id=14100254[An Alternative Approach to Rate Limiting]
https://news.ycombinator.com/item?id=14077863[Programming in the Point-Free Style]
https://news.ycombinator.com/item?id=14084526[Fourier transform – A math tool used in optics, MP3s, JPEGs and more (2013)]

== documentation
=== command line notes
create anonymous function
requires setopt RC_EXPAND_PARAM in .zshrc
--
(){echo $@.txt} a b c
--
outputs
--
a.txt b.txt c.txt
--

=== ssh key privacy
--
    # Ignore SSH keys unless specified in Host subsection
    IdentitiesOnly yes

    # Send your public key to github only
    Host github.com
        IdentityFile ~/.ssh/id_rsa
--

=== asciidoc user guide
http://www.methods.co.nz/asciidoc/userguide.html[AsciiDoc User Guide]

=== zsh git customization
https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples

== libraries
=== dependency injection
https://google.github.io/dagger/users-guide

=== code coverage
http://www.eclemma.org/

=== raft consensus algorithm
https://github.com/atomix/copycat

=== serialization
https://google.github.io/flatbuffers/index.html
https://fi.java.net/
https://capnproto.org/

=== structured logging
http://syslog4j.org/
https://logging.apache.org/log4j/2.x/
