import java.awt.GraphicsEnvironment;
import java.io.Console;

import javax.swing.JOptionPane;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
     Console console = System.console();
     System.out.println("is headless: " + GraphicsEnvironment.isHeadless());
     System.out.println("console: " + System.console().readPassword("enter: ").length);
//     if (!GraphicsEnvironment.isHeadless()) {
//      JOptionPane.showMessageDialog(null, "graphical environment");
//     } else if (console != null) {
//     if (console != null) {
//      console.format("console environment");
//     } else {
//      System.out.println("no console");
//     }
    }
}
