= readme

== run from cmd
code\misc\bin>java -cp ".;C:\Users\a\.gradle\caches\modules-2\files-2.1\com.google.inject\guice\4.1.0\eeb69005da379a10071aa4948c48d89250febb07\guice-4.1.0.jar;C:\Users\a\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.9.1\c041978c686866ee8534f538c6220238db3bb6be\log4j-core-2.9.1.jar;C:\Users\a\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.9.1\7a2999229464e7a324aa503c0a52ec0f05efe7bd\log4j-api-2.9.1.jar;C:\Users\a\.gradle\caches\modules-2\files-2.1\com.ibm.icu\icu4j\59.1\6f06e820cf4c8968bbbaae66ae0b33f6a256b57f\icu4j-59.1.jar;" -Dheadless=true root.Main

Oct 04, 2017 12:04:39 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.list-cell' in stylesheet jar:file:/C:/Program%20Files/Java/jdk1.8.0_25/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Oct 04, 2017 12:04:39 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-accent' while resolving lookups for '-fx-background-color' from rule '*.combo-box-popup>*.list-view>*.virtual-flow>*.clipped-container>*.sheet>*.list-cell:hover:filled:selected' in stylesheet jar:file:/C:/Program%20Files/Java/jdk1.8.0_25/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss


== todo

== structures
- map
- rope
- gap buffer
- piece table
- 2-3 tree
- B tree
- trie
- skip list
- red-black tree
- splay tree
- binomial heap
- fibonacci heap
- interval tree = R tree where limit to one dimension (time)
- bit vector
- Deterministic acyclic finite state automaton
- hash table
- merkle
- finger tree
- k-ary tree
- suffix tree
- patricia tree = radix tree where radix = 2

== algorithms
- serialize tree
- conversion between binary tree and doubly linked list http://www.geeksforgeeks.org/binary-tree-data-structure/#construction

== links
- https://github.com/arximboldi/ewig
- https://sinusoid.es/immer/

== tests
----
gradlew test --continuous
----

== run
----
gradlew run
----

== distribute
create distributable binaries in `build/install`
----
gradlew installDist
----
